//
// Generated by JTB 1.3.2
//

package mips.syntaxtree;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence
 * implement.
 */
public interface NodeListInterface extends Node {
   public void addNode(Node n);
   public Node elementAt(int i);
   public java.util.Enumeration<Node> elements();
   public int size();

   public void accept(mips.visitor.Visitor v);
   public <R,A> R accept(mips.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(mips.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(mips.visitor.GJVoidVisitor<A> v, A argu);
}

